apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoclient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoclient
  template:
    metadata:
      labels:
        app: mongoclient
    spec:
      nodeName: k8sworker
      containers:
      - image: mongoclient/mongoclient
        name: mongoclient
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://mongo-db:27017"
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: mongoclient
  labels:
    app: mongoclient
spec:
  selector:
    app: mongoclient
  ports:
  - name: service
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
    
