apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: zookeeper
        name: zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOO_MY_ID
          value: "1"
        - name: ZOO_PORT
          value: "2181"
        - name: ZOO_SERVERS
          value: "server.1=zookeeper:2888:3888;2181"
        volumeMounts:
        - name: data
          mountPath: /data
        - name: datalog
          mountPath: /datalog
      volumes:
      - name: data
        hostPath:
          path: /var/tmp/zookeeper/data
          type: DirectoryOrCreate
      - name: datalog
        hostPath:
          path: /var/tmp/zookeeper/datalog
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - name: service
    port: 2181
    protocol: TCP
    targetPort: 2181
  type: LoadBalancer